### PR TITLE
Style edits

### PR DESCRIPTION
**Pull request by ShiraZacks**

### CODE REVIEW

**Comment by abe-101** [comment]
Can you change to color from orange to something more muted?
Maybe like Raspberry

**Comment by abe-101** [comment]
WhatsApp Image 2023-08-03 at 3 41 15 PM
Can center the 3 columns to be in middle of the box (a bit lower)

**Comment by ShiraZacks** [comment]
> Can you change to color from orange to something more muted? Maybe like Raspberry

Done

**Comment by ShiraZacks** [comment]
> WhatsApp Image 2023-08-03 at 3 41 15 PM Can center the 3 columns to be in middle of the box (a bit lower)

Done

**Comment by ShiraZacks** [comment]
> WhatsApp Image 2023-08-03 at 3 41 15 PM Can center the 3 columns to be in middle of the box (a bit lower)

Done

**Review by abe-101 — APPROVED** [review]

**Pull request merged**
